<?php

return [
    // 欧洲
    'AT' => 'de-AT,de;q=0.9,en;q=0.8',  // 奥地利
    'BE' => 'nl-BE,fr-BE;q=0.9,nl;q=0.8,fr;q=0.7,en;q=0.6',  // 比利时（双语：荷兰语、法语）
    'BG' => 'bg-BG,bg;q=0.9,en;q=0.8',  // 保加利亚
    'CH' => 'de-CH,fr-CH;q=0.9,it-CH;q=0.8,de;q=0.7,fr;q=0.6,it;q=0.5,en;q=0.4',  // 瑞士（多语言）
    'CZ' => 'cs-CZ,cs;q=0.9,en;q=0.8',  // 捷克
    'DE' => 'de-DE,de;q=0.9,en;q=0.8',  // 德国
    'DK' => 'da-DK,da;q=0.9,en;q=0.8',  // 丹麦
    'ES' => 'es-ES,es;q=0.9,en;q=0.8',  // 西班牙
    'FI' => 'fi-FI,fi;q=0.9,en;q=0.8',  // 芬兰
    'FR' => 'fr-FR,fr;q=0.9,en;q=0.8',  // 法国
    'GB' => 'en-GB,en;q=0.9',  // 英国
    'GR' => 'el-GR,el;q=0.9,en;q=0.8',  // 希腊
    'HU' => 'hu-HU,hu;q=0.9,en;q=0.8',  // 匈牙利
    'IE' => 'en-IE,en;q=0.9,ga;q=0.8',  // 爱尔兰
    'IT' => 'it-IT,it;q=0.9,en;q=0.8',  // 意大利
    'LI' => 'de-LI,de;q=0.9,en;q=0.8',  // 列支敦士登
    'LU' => 'fr-LU,de-LU;q=0.9,fr;q=0.8,de;q=0.7,en;q=0.6',  // 卢森堡
    'NL' => 'nl-NL,nl;q=0.9,en;q=0.8',  // 荷兰
    'NO' => 'nb-NO,nb;q=0.9,nn-NO;q=0.8,nn;q=0.7,en;q=0.6',  // 挪威
    'PL' => 'pl-PL,pl;q=0.9,en;q=0.8',  // 波兰
    'PT' => 'pt-PT,pt;q=0.9,en;q=0.8',  // 葡萄牙
    'RO' => 'ro-RO,ro;q=0.9,en;q=0.8',  // 罗马尼亚
    'RU' => 'ru-RU,ru;q=0.9,en;q=0.8',  // 俄罗斯
    'SE' => 'sv-SE,sv;q=0.9,en;q=0.8',  // 瑞典
    'SK' => 'sk-SK,sk;q=0.9,en;q=0.8',  // 斯洛伐克
    'SI' => 'sl-SI,sl;q=0.9,en;q=0.8',  // 斯洛文尼亚
    'TR' => 'tr-TR,tr;q=0.9,en;q=0.8',  // 土耳其
    'UA' => 'uk-UA,uk;q=0.9,ru;q=0.8,en;q=0.7',  // 乌克兰
    'HR' => 'hr-HR,hr;q=0.9,en;q=0.8',  // 克罗地亚
    'RS' => 'sr-RS,sr;q=0.9,en;q=0.8',  // 塞尔维亚
    'IS' => 'is-IS,is;q=0.9,en;q=0.8',  // 冰岛
    'CY' => 'el-CY,el;q=0.9,tr-CY;q=0.8,en;q=0.7',  // 塞浦路斯
    'MT' => 'mt-MT,mt;q=0.9,en;q=0.8',  // 马耳他
    'AD' => 'ca-AD,ca;q=0.9,es;q=0.8,fr;q=0.7,en;q=0.6',  // 安道尔
    'AL' => 'sq-AL,sq;q=0.9,en;q=0.8',  // 阿尔巴尼亚
    'BA' => 'bs-BA,bs;q=0.9,hr-BA;q=0.8,sr-BA;q=0.7,en;q=0.6',  // 波斯尼亚和黑塞哥维那
    'EE' => 'et-EE,et;q=0.9,en;q=0.8',  // 爱沙尼亚
    'FO' => 'fo-FO,fo;q=0.9,da;q=0.8,en;q=0.7',  // 法罗群岛
    'GI' => 'en-GI,en;q=0.9,es;q=0.8',  // 直布罗陀
    'LT' => 'lt-LT,lt;q=0.9,en;q=0.8',  // 立陶宛
    'LV' => 'lv-LV,lv;q=0.9,en;q=0.8',  // 拉脱维亚
    'MC' => 'fr-MC,fr;q=0.9,en;q=0.8',  // 摩纳哥
    'MD' => 'ro-MD,ro;q=0.9,ru;q=0.8,en;q=0.7',  // 摩尔多瓦
    'ME' => 'sr-ME,sr;q=0.9,en;q=0.8',  // 黑山
    'MK' => 'mk-MK,mk;q=0.9,en;q=0.8',  // 北马其顿
    'SM' => 'it-SM,it;q=0.9,en;q=0.8',  // 圣马力诺
    'VA' => 'it-VA,it;q=0.9,la;q=0.8,en;q=0.7',  // 梵蒂冈
    'XK' => 'sq-XK,sq;q=0.9,sr-XK;q=0.8,en;q=0.7',  // 科索沃

    // 北美
    'CA' => 'en-CA,fr-CA;q=0.9,en;q=0.8,fr;q=0.7',  // 加拿大（双语：英语、法语）
    'US' => 'en-US,en;q=0.9',  // 美国
    'MX' => 'es-MX,es;q=0.9,en;q=0.8',  // 墨西哥
    'AG' => 'en-AG,en;q=0.9',  // 安提瓜和巴布达
    'BB' => 'en-BB,en;q=0.9',  // 巴巴多斯
    'BS' => 'en-BS,en;q=0.9',  // 巴哈马
    'BZ' => 'en-BZ,en;q=0.9,es;q=0.8',  // 伯利兹
    'CU' => 'es-CU,es;q=0.9,en;q=0.8',  // 古巴
    'DM' => 'en-DM,en;q=0.9',  // 多米尼克
    'DO' => 'es-DO,es;q=0.9,en;q=0.8',  // 多米尼加共和国
    'GD' => 'en-GD,en;q=0.9',  // 格林纳达
    'GT' => 'es-GT,es;q=0.9,en;q=0.8',  // 危地马拉
    'HT' => 'ht-HT,ht;q=0.9,fr-HT;q=0.8,en;q=0.7',  // 海地
    'HN' => 'es-HN,es;q=0.9,en;q=0.8',  // 洪都拉斯
    'JM' => 'en-JM,en;q=0.9',  // 牙买加
    'KN' => 'en-KN,en;q=0.9',  // 圣基茨和尼维斯
    'LC' => 'en-LC,en;q=0.9',  // 圣卢西亚
    'NI' => 'es-NI,es;q=0.9,en;q=0.8',  // 尼加拉瓜
    'PA' => 'es-PA,es;q=0.9,en;q=0.8',  // 巴拿马
    'PR' => 'es-PR,es;q=0.9,en;q=0.8',  // 波多黎各
    'SV' => 'es-SV,es;q=0.9,en;q=0.8',  // 萨尔瓦多
    'TT' => 'en-TT,en;q=0.9',  // 特立尼达和多巴哥
    'VC' => 'en-VC,en;q=0.9',  // 圣文森特和格林纳丁斯

    // 南美
    'AR' => 'es-AR,es;q=0.9,en;q=0.8',  // 阿根廷
    'BO' => 'es-BO,es;q=0.9,en;q=0.8',  // 玻利维亚
    'BR' => 'pt-BR,pt;q=0.9,en;q=0.8',  // 巴西
    'CL' => 'es-CL,es;q=0.9,en;q=0.8',  // 智利
    'CO' => 'es-CO,es;q=0.9,en;q=0.8',  // 哥伦比亚
    'PE' => 'es-PE,es;q=0.9,en;q=0.8',  // 秘鲁
    'VE' => 'es-VE,es;q=0.9,en;q=0.8',  // 委内瑞拉
    'UY' => 'es-UY,es;q=0.9,en;q=0.8',  // 乌拉圭
    'PY' => 'es-PY,es;q=0.9,en;q=0.8',  // 巴拉圭
    'EC' => 'es-EC,es;q=0.9,en;q=0.8',  // 厄瓜多尔
    'CR' => 'es-CR,es;q=0.9,en;q=0.8',  // 哥斯达黎加
    'GY' => 'en-GY,en;q=0.9',  // 圭亚那
    'SR' => 'nl-SR,nl;q=0.9,en;q=0.8',  // 苏里南
    'FK' => 'en-FK,en;q=0.9',  // 福克兰群岛
    'GF' => 'fr-GF,fr;q=0.9,en;q=0.8',  // 法属圭亚那

    // 亚洲
    'CN' => 'zh-CN,zh;q=0.9,en;q=0.8',  // 中国
    'HK' => 'zh-HK,zh;q=0.9,en;q=0.8',  // 香港
    'ID' => 'id-ID,id;q=0.9,en;q=0.8',  // 印度尼西亚
    'IL' => 'he-IL,he;q=0.9,en;q=0.8',  // 以色列
    'IN' => 'hi-IN,hi;q=0.9,en-IN;q=0.8,en;q=0.7',  // 印度
    'JP' => 'ja-JP,ja;q=0.9,en;q=0.8',  // 日本
    'KR' => 'ko-KR,ko;q=0.9,en;q=0.8',  // 韩国
    'MY' => 'ms-MY,ms;q=0.9,en-MY;q=0.8,en;q=0.7',  // 马来西亚
    'SA' => 'ar-SA,ar;q=0.9,en;q=0.8',  // 沙特阿拉伯
    'SG' => 'en-SG,zh-SG;q=0.9,en;q=0.8,zh;q=0.7',  // 新加坡（英语和中文）
    'TH' => 'th-TH,th;q=0.9,en;q=0.8',  // 泰国
    'TW' => 'zh-TW,zh;q=0.9,en;q=0.8',  // 台湾
    'VN' => 'vi-VN,vi;q=0.9,en;q=0.8',  // 越南
    'PH' => 'en-PH,fil-PH;q=0.9,en;q=0.8,fil;q=0.7',  // 菲律宾
    'BD' => 'bn-BD,bn;q=0.9,en;q=0.8',  // 孟加拉国
    'LK' => 'si-LK,si;q=0.9,ta-LK;q=0.8,en;q=0.7',  // 斯里兰卡
    'KH' => 'km-KH,km;q=0.9,en;q=0.8',  // 柬埔寨
    'MM' => 'my-MM,my;q=0.9,en;q=0.8',  // 缅甸
    'NP' => 'ne-NP,ne;q=0.9,en;q=0.8',  // 尼泊尔
    'PK' => 'ur-PK,ur;q=0.9,en;q=0.8',  // 巴基斯坦
    'MN' => 'mn-MN,mn;q=0.9,en;q=0.8',  // 蒙古
    'KZ' => 'kk-KZ,kk;q=0.9,ru;q=0.8,en;q=0.7',  // 哈萨克斯坦
    'UZ' => 'uz-UZ,uz;q=0.9,ru;q=0.8,en;q=0.7',  // 乌兹别克斯坦
    'GE' => 'ka-GE,ka;q=0.9,en;q=0.8',  // 格鲁吉亚
    'AM' => 'hy-AM,hy;q=0.9,en;q=0.8',  // 亚美尼亚
    'AZ' => 'az-AZ,az;q=0.9,en;q=0.8',  // 阿塞拜疆
    'AF' => 'fa-AF,fa;q=0.9,ps;q=0.8,en;q=0.7',  // 阿富汗
    'BH' => 'ar-BH,ar;q=0.9,en;q=0.8',  // 巴林
    'BN' => 'ms-BN,ms;q=0.9,en;q=0.8',  // 文莱
    'BT' => 'dz-BT,dz;q=0.9,en;q=0.8',  // 不丹
    'IO' => 'en-IO,en;q=0.9',  // 英属印度洋领地
    'KP' => 'ko-KP,ko;q=0.9',  // 朝鲜
    'KG' => 'ky-KG,ky;q=0.9,ru;q=0.8,en;q=0.7',  // 吉尔吉斯斯坦
    'LA' => 'lo-LA,lo;q=0.9,en;q=0.8',  // 老挝
    'MO' => 'zh-MO,zh;q=0.9,en;q=0.8,pt;q=0.7',  // 澳门
    'MV' => 'dv-MV,dv;q=0.9,en;q=0.8',  // 马尔代夫
    'OM' => 'ar-OM,ar;q=0.9,en;q=0.8',  // 阿曼
    'PS' => 'ar-PS,ar;q=0.9,en;q=0.8',  // 巴勒斯坦
    'SY' => 'ar-SY,ar;q=0.9,en;q=0.8',  // 叙利亚
    'TJ' => 'tg-TJ,tg;q=0.9,ru;q=0.8,en;q=0.7',  // 塔吉克斯坦
    'TL' => 'pt-TL,pt;q=0.9,en;q=0.8',  // 东帝汶
    'TM' => 'tk-TM,tk;q=0.9,ru;q=0.8,en;q=0.7',  // 土库曼斯坦
    'YE' => 'ar-YE,ar;q=0.9,en;q=0.8',  // 也门

    // 大洋洲
    'AU' => 'en-AU,en;q=0.9',  // 澳大利亚
    'NZ' => 'en-NZ,en;q=0.9',  // 新西兰
    'FJ' => 'en-FJ,en;q=0.9,fj;q=0.8',  // 斐济
    'FM' => 'en-FM,en;q=0.9',  // 密克罗尼西亚联邦
    'KI' => 'en-KI,en;q=0.9',  // 基里巴斯
    'MH' => 'en-MH,en;q=0.9',  // 马绍尔群岛
    'NR' => 'en-NR,en;q=0.9,na;q=0.8',  // 瑙鲁
    'NU' => 'en-NU,en;q=0.9',  // 纽埃
    'PF' => 'fr-PF,fr;q=0.9,en;q=0.8',  // 法属波利尼西亚
    'PG' => 'en-PG,en;q=0.9,ho;q=0.8',  // 巴布亚新几内亚
    'PW' => 'en-PW,en;q=0.9',  // 帕劳
    'SB' => 'en-SB,en;q=0.9',  // 所罗门群岛
    'TO' => 'en-TO,en;q=0.9',  // 汤加
    'TV' => 'en-TV,en;q=0.9',  // 图瓦卢
    'VU' => 'en-VU,en;q=0.9,fr;q=0.8',  // 瓦努阿图
    'WS' => 'en-WS,en;q=0.9,sm;q=0.8',  // 萨摩亚
    'NC' => 'fr-NC,fr;q=0.9,en;q=0.8',  // 新喀里多尼亚

    // 中东
    'AE' => 'ar-AE,ar;q=0.9,en;q=0.8',  // 阿联酋
    'EG' => 'ar-EG,ar;q=0.9,en;q=0.8',  // 埃及
    'JO' => 'ar-JO,ar;q=0.9,en;q=0.8',  // 约旦
    'KW' => 'ar-KW,ar;q=0.9,en;q=0.8',  // 科威特
    'QA' => 'ar-QA,ar;q=0.9,en;q=0.8',  // 卡塔尔
    'IQ' => 'ar-IQ,ar;q=0.9,en;q=0.8',  // 伊拉克
    'IR' => 'fa-IR,fa;q=0.9,en;q=0.8',  // 伊朗
    'LB' => 'ar-LB,ar;q=0.9,fr-LB;q=0.8,en;q=0.7',  // 黎巴嫩

    // 非洲
    'ZA' => 'en-ZA,en;q=0.9,af;q=0.8',  // 南非
    'MA' => 'ar-MA,ar;q=0.9,fr;q=0.8,en;q=0.7',  // 摩洛哥
    'NG' => 'en-NG,en;q=0.9',  // 尼日利亚
    'DZ' => 'ar-DZ,ar;q=0.9,fr;q=0.8,en;q=0.7',  // 阿尔及利亚
    'KE' => 'sw-KE,sw;q=0.9,en-KE;q=0.8,en;q=0.7',  // 肯尼亚
    'TN' => 'ar-TN,ar;q=0.9,fr;q=0.8,en;q=0.7',  // 突尼斯
    'GH' => 'en-GH,en;q=0.9',  // 加纳
    'ET' => 'am-ET,am;q=0.9,en;q=0.8',  // 埃塞俄比亚
    'AO' => 'pt-AO,pt;q=0.9,en;q=0.8',  // 安哥拉
    'BF' => 'fr-BF,fr;q=0.9,en;q=0.8',  // 布基纳法索
    'BI' => 'fr-BI,fr;q=0.9,en;q=0.8',  // 布隆迪
    'BJ' => 'fr-BJ,fr;q=0.9,en;q=0.8',  // 贝宁
    'BW' => 'en-BW,en;q=0.9',  // 博茨瓦纳
    'CD' => 'fr-CD,fr;q=0.9,en;q=0.8',  // 刚果民主共和国
    'CF' => 'fr-CF,fr;q=0.9,en;q=0.8',  // 中非共和国
    'CG' => 'fr-CG,fr;q=0.9,en;q=0.8',  // 刚果共和国
    'CI' => 'fr-CI,fr;q=0.9,en;q=0.8',  // 科特迪瓦
    'CM' => 'fr-CM,fr;q=0.9,en;q=0.8',  // 喀麦隆
    'CV' => 'pt-CV,pt;q=0.9,en;q=0.8',  // 佛得角
    'DJ' => 'fr-DJ,fr;q=0.9,ar;q=0.8,en;q=0.7',  // 吉布提
    'ER' => 'ti-ER,ti;q=0.9,en;q=0.8',  // 厄立特里亚
    'GA' => 'fr-GA,fr;q=0.9,en;q=0.8',  // 加蓬
    'GM' => 'en-GM,en;q=0.9',  // 冈比亚
    'GN' => 'fr-GN,fr;q=0.9,en;q=0.8',  // 几内亚
    'GQ' => 'es-GQ,es;q=0.9,en;q=0.8',  // 赤道几内亚
    'GW' => 'pt-GW,pt;q=0.9,en;q=0.8',  // 几内亚比绍
    'LR' => 'en-LR,en;q=0.9',  // 利比里亚
    'LS' => 'en-LS,en;q=0.9',  // 莱索托
    'LY' => 'ar-LY,ar;q=0.9,en;q=0.8',  // 利比亚
    'MG' => 'fr-MG,fr;q=0.9,mg;q=0.8,en;q=0.7',  // 马达加斯加
    'ML' => 'fr-ML,fr;q=0.9,en;q=0.8',  // 马里
    'MR' => 'ar-MR,ar;q=0.9,fr;q=0.8,en;q=0.7',  // 毛里塔尼亚
    'MU' => 'en-MU,en;q=0.9,fr;q=0.8',  // 毛里求斯
    'MW' => 'en-MW,en;q=0.9',  // 马拉维
    'MZ' => 'pt-MZ,pt;q=0.9,en;q=0.8',  // 莫桑比克
    'NA' => 'en-NA,en;q=0.9,af;q=0.8',  // 纳米比亚
    'NE' => 'fr-NE,fr;q=0.9,en;q=0.8',  // 尼日尔
    'RW' => 'fr-RW,fr;q=0.9,en;q=0.8,rw;q=0.7',  // 卢旺达
    'SC' => 'en-SC,en;q=0.9,fr;q=0.8',  // 塞舌尔
    'SD' => 'ar-SD,ar;q=0.9,en;q=0.8',  // 苏丹
    'SL' => 'en-SL,en;q=0.9',  // 塞拉利昂
    'SN' => 'fr-SN,fr;q=0.9,en;q=0.8',  // 塞内加尔
    'SO' => 'so-SO,so;q=0.9,en;q=0.8',  // 索马里
    'SS' => 'en-SS,en;q=0.9',  // 南苏丹
    'ST' => 'pt-ST,pt;q=0.9,en;q=0.8',  // 圣多美和普林西比
    'SZ' => 'en-SZ,en;q=0.9',  // 斯威士兰/埃斯瓦蒂尼
    'TD' => 'fr-TD,fr;q=0.9,en;q=0.8',  // 乍得
    'TG' => 'fr-TG,fr;q=0.9,en;q=0.8',  // 多哥
    'TZ' => 'sw-TZ,sw;q=0.9,en;q=0.8',  // 坦桑尼亚
    'UG' => 'en-UG,en;q=0.9,sw;q=0.8',  // 乌干达
    'ZM' => 'en-ZM,en;q=0.9',  // 赞比亚
    'ZW' => 'en-ZW,en;q=0.9,sn;q=0.8',  // 津巴布韦

    // 加勒比地区
    'AI' => 'en-AI,en;q=0.9',  // 安圭拉
    'AW' => 'nl-AW,nl;q=0.9,en;q=0.8',  // 阿鲁巴
    'BL' => 'fr-BL,fr;q=0.9,en;q=0.8',  // 圣巴泰勒米
    'BQ' => 'nl-BQ,nl;q=0.9,en;q=0.8',  // 博内尔、圣尤斯特歇斯和萨巴
    'CW' => 'nl-CW,nl;q=0.9,en;q=0.8',  // 库拉索
    'GP' => 'fr-GP,fr;q=0.9,en;q=0.8',  // 瓜德罗普
    'KY' => 'en-KY,en;q=0.9',  // 开曼群岛
    'MF' => 'fr-MF,fr;q=0.9,en;q=0.8',  // 法属圣马丁
    'MQ' => 'fr-MQ,fr;q=0.9,en;q=0.8',  // 马提尼克
    'MS' => 'en-MS,en;q=0.9',  // 蒙特塞拉特
    'SX' => 'nl-SX,nl;q=0.9,en;q=0.8',  // 荷属圣马丁
    'TC' => 'en-TC,en;q=0.9',  // 特克斯和凯科斯群岛
    'VG' => 'en-VG,en;q=0.9',  // 英属维尔京群岛
    'VI' => 'en-VI,en;q=0.9',  // 美属维尔京群岛

    // 其他地区和特殊领土
    'AS' => 'en-AS,en;q=0.9,sm;q=0.8',  // 美属萨摩亚
    'AX' => 'sv-AX,sv;q=0.9,fi;q=0.8,en;q=0.7',  // 奥兰群岛
    'BV' => 'no-BV,no;q=0.9,en;q=0.8',  // 布韦岛
    'CC' => 'en-CC,en;q=0.9',  // 科科斯(基林)群岛
    'CX' => 'en-CX,en;q=0.9',  // 圣诞岛
    'GG' => 'en-GG,en;q=0.9',  // 根西岛
    'GL' => 'kl-GL,kl;q=0.9,da;q=0.8,en;q=0.7',  // 格陵兰
    'GS' => 'en-GS,en;q=0.9',  // 南乔治亚和南桑威奇群岛
    'GU' => 'en-GU,en;q=0.9,ch;q=0.8',  // 关岛
    'HM' => 'en-HM,en;q=0.9',  // 赫德岛和麦克唐纳群岛
    'IM' => 'en-IM,en;q=0.9,gv;q=0.8',  // 马恩岛
    'JE' => 'en-JE,en;q=0.9',  // 泽西岛
    'MP' => 'en-MP,en;q=0.9,ch;q=0.8',  // 北马里亚纳群岛
    'PM' => 'fr-PM,fr;q=0.9,en;q=0.8',  // 圣皮埃尔和密克隆
    'PN' => 'en-PN,en;q=0.9',  // 皮特凯恩群岛
    'RE' => 'fr-RE,fr;q=0.9,en;q=0.8',  // 留尼汪
    'SH' => 'en-SH,en;q=0.9',  // 圣赫勒拿
    'SJ' => 'no-SJ,no;q=0.9,en;q=0.8',  // 斯瓦尔巴和扬马延
    'TF' => 'fr-TF,fr;q=0.9,en;q=0.8',  // 法属南部领地
    'TK' => 'en-TK,en;q=0.9',  // 托克劳
    'UM' => 'en-UM,en;q=0.9',  // 美国本土外小岛屿
    'WF' => 'fr-WF,fr;q=0.9,en;q=0.8',  // 瓦利斯和富图纳
    'YT' => 'fr-YT,fr;q=0.9,en;q=0.8',  // 马约特
];
